feature: support custom lua TT filters.
openresty/lemplate pull request #1
Opened 2017-04-06 21:23 UTC by ingydotnet

Example:
```lua
lemplate = require('my.templates')
lemplate.filters['upper'] = function(str, args)
    return string.upper(str)
end
lemplate.process('[% "i like pie" | upper %]')
```

2017-04-06 21:30 UTC, agentzh approved these changes

2017-04-06 21:30 UTC, agentzh commented
@doujiang24 Have a look at this :)

@ingydotnet Thanks!

2017-04-07 10:29 UTC, doujiang24 commented
@ingydotnet works fine on my side. one question: seems we should also update [lemplate](https://github.com/openresty/lemplate/blob/master/lemplate).

2017-04-07 18:07 UTC, ingydotnet commented
Updated. Please Review.

2017-04-07 19:45 UTC, agentzh requested changes

2017-04-07 19:45 UTC, agentzh commented on lib/Lemplate.pm
> +            else
We should not use `else` when the previous branch never falls through :) I think we encountered this before ;)

2017-04-08 03:09 UTC, ingydotnet commented on lib/Lemplate.pm
> +            else
Fixed. Please review.

2017-04-08 05:30 UTC, agentzh commented
@ingydotnet Will rebase to the latest master and resolve those conflicts? Then I think it's good to merge. Thanks a lot!

2017-04-10 17:42 UTC, ingydotnet commented
Done. Please review.

2017-04-10 19:05 UTC, agentzh commented
@ingydotnet Merged. Thanks!

2017-04-10 19:05 UTC, closed without merging