bugfix: the VMethod push should returns empty string.
openresty/lemplate pull request #3
Opened 2017-04-19 04:28 UTC by doujiang24

2017-04-19 07:16 UTC, doujiang24 commented
travis failed when run test with perl 5.8: `Devel::Cover 0.001 is not supported on perl 5.008009`.
https://travis-ci.org/openresty/lemplate/jobs/223442906
so I removed perl 5.8, hope this is acceptable :)

2017-04-19 20:35 UTC, agentzh commented
@doujiang24 We need to test perl 5.8. We just need to remove the `Devel::Cover` thing which was inherited from Jemplate. We don't really need it.

I've already fixed the travis CI build of this project in master.

2017-04-19 20:38 UTC, agentzh requested changes

2017-04-19 20:38 UTC, agentzh commented on t/vmethods.t
>  --- out chomp
Will you add some tests for pushing multiple elements into the array?

2017-04-19 20:38 UTC, agentzh commented on .travis.yml
> -- 5.8
We no longer need this since the master is already working with perl 5.8 in traivs ci.

2017-04-20 03:58 UTC, doujiang24 commented
@agentzh All done & rebased :)

2017-04-20 04:06 UTC, agentzh commented
@doujiang24 Merged. Thanks!

2017-04-20 04:06 UTC, closed without merging